package PoliceStationManagement;
import SQLPackage.*;
import PoliceStationManagement.MainPage;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class AccusedJFrame extends javax.swing.JFrame {

    
    public AccusedJFrame() {
        initComponents();
        setTitle("Accused Form");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_accused = new javax.swing.JPanel();
        jTextField_caseId = new javax.swing.JTextField();
        jLabel_PresentDistrict1 = new javax.swing.JLabel();
        jButton_save = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jTextField_presentThana = new javax.swing.JTextField();
        jTextField_presentAddress = new javax.swing.JTextField();
        jTextField4_thana = new javax.swing.JTextField();
        jTextField_village = new javax.swing.JTextField();
        jTextField_fathersName = new javax.swing.JTextField();
        jTextField_age = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jLabel_PresentDistrict = new javax.swing.JLabel();
        jLabel_PresentThana = new javax.swing.JLabel();
        jLabel_PresentAdress = new javax.swing.JLabel();
        jLabel_District = new javax.swing.JLabel();
        jLabel_Thana = new javax.swing.JLabel();
        jLabel_Village = new javax.swing.JLabel();
        jLabel_fathersName = new javax.swing.JLabel();
        jLabel_age = new javax.swing.JLabel();
        jLabel_AccusedName = new javax.swing.JLabel();
        jLabel_accused = new javax.swing.JLabel();
        jComboBox_district = new javax.swing.JComboBox<>();
        jComboBox_presentDistrict = new javax.swing.JComboBox<>();
        jLabel_logo = new javax.swing.JLabel();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_accused.setLayout(null);

        jTextField_caseId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel_accused.add(jTextField_caseId);
        jTextField_caseId.setBounds(290, 160, 550, 40);

        jLabel_PresentDistrict1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_PresentDistrict1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PresentDistrict1.setText("Case No * :");
        jPanel_accused.add(jLabel_PresentDistrict1);
        jLabel_PresentDistrict1.setBounds(70, 160, 150, 22);

        jButton_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_save.setText("SUBMIT");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });
        jPanel_accused.add(jButton_save);
        jButton_save.setBounds(980, 770, 190, 60);

        jButton_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_back.setText("BACK");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        jPanel_accused.add(jButton_back);
        jButton_back.setBounds(60, 780, 200, 60);

        jTextField_presentThana.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel_accused.add(jTextField_presentThana);
        jTextField_presentThana.setBounds(290, 640, 550, 40);

        jTextField_presentAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel_accused.add(jTextField_presentAddress);
        jTextField_presentAddress.setBounds(290, 580, 550, 40);

        jTextField4_thana.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel_accused.add(jTextField4_thana);
        jTextField4_thana.setBounds(290, 460, 550, 40);

        jTextField_village.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel_accused.add(jTextField_village);
        jTextField_village.setBounds(290, 400, 550, 40);

        jTextField_fathersName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel_accused.add(jTextField_fathersName);
        jTextField_fathersName.setBounds(290, 340, 550, 40);

        jTextField_age.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ageActionPerformed(evt);
            }
        });
        jPanel_accused.add(jTextField_age);
        jTextField_age.setBounds(290, 280, 550, 40);

        jTextField_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel_accused.add(jTextField_name);
        jTextField_name.setBounds(290, 220, 550, 40);

        jLabel_PresentDistrict.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_PresentDistrict.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PresentDistrict.setText("Present District:");
        jPanel_accused.add(jLabel_PresentDistrict);
        jLabel_PresentDistrict.setBounds(70, 710, 150, 22);

        jLabel_PresentThana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_PresentThana.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PresentThana.setText("Present Thana:");
        jPanel_accused.add(jLabel_PresentThana);
        jLabel_PresentThana.setBounds(70, 650, 140, 22);

        jLabel_PresentAdress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_PresentAdress.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PresentAdress.setText("Present Adress:");
        jPanel_accused.add(jLabel_PresentAdress);
        jLabel_PresentAdress.setBounds(70, 590, 142, 22);

        jLabel_District.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_District.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_District.setText("District:");
        jPanel_accused.add(jLabel_District);
        jLabel_District.setBounds(70, 530, 160, 22);

        jLabel_Thana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Thana.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Thana.setText("Thana:");
        jPanel_accused.add(jLabel_Thana);
        jLabel_Thana.setBounds(70, 470, 150, 22);

        jLabel_Village.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Village.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Village.setText("Village:");
        jPanel_accused.add(jLabel_Village);
        jLabel_Village.setBounds(70, 410, 160, 30);

        jLabel_fathersName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_fathersName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fathersName.setText("Father's Name:");
        jPanel_accused.add(jLabel_fathersName);
        jLabel_fathersName.setBounds(70, 350, 160, 30);

        jLabel_age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_age.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_age.setText("Age:");
        jPanel_accused.add(jLabel_age);
        jLabel_age.setBounds(70, 290, 140, 22);

        jLabel_AccusedName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_AccusedName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AccusedName.setText("Name:");
        jPanel_accused.add(jLabel_AccusedName);
        jLabel_AccusedName.setBounds(70, 230, 160, 22);

        jLabel_accused.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_accused.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_accused.setText("ACCUSED FORM:");
        jPanel_accused.add(jLabel_accused);
        jLabel_accused.setBounds(60, 50, 310, 40);

        jComboBox_district.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox_district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--","Barguna", "Barisal","Bhola","Jhalokathi","Potuakhali", "Pirojpur","Bandarban","Brahmanbaria","Chandpur","Chittagong","Comilla", "Coxs Bazar",
            "Feni", "Khagrachhari","Lakshmipur","Noakhali","Rangamati", "Dhaka","Faridpur", "Gazipur","Gopalganj","Kishorganj","Madaripur", "Manikganj",
            "Munshiganj", "Narayanganj","Narsingdi","Rajbari","Shariatpur", "Tangail","Bagerhat", "Chuadanga","Jessore","Jhenaidaha","Khulna", "Kushtia",
            "Magura", "Meherpur","Narail","Satkhira","Jamalpur", "Mymensingh","Netrokona", "Sherpur","Bogura","Joypurhat","Naogan", "Natore",
            "Chapai Nawab Ganj", "Pabna","Rajshahi","Sirajganj","Dinajpur", "Gaibandha","Kurigram","Nilphamari","Lalmonirhaat","Panchagarh","Rangpur","Thakurgaon",
            "Habiganj","Moulovibajar", "Sunamganj","Sylhet" }));
jPanel_accused.add(jComboBox_district);
jComboBox_district.setBounds(290, 520, 550, 40);

jComboBox_presentDistrict.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
jComboBox_presentDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"--Choose--","Barguna", "Barisal","Bhola","Jhalokathi","Potuakhali", "Pirojpur","Bandarban","Brahmanbaria","Chandpur","Chittagong","Comilla", "Coxs Bazar",
    "Feni", "Khagrachhari","Lakshmipur","Noakhali","Rangamati", "Dhaka","Faridpur", "Gazipur","Gopalganj","Kishorganj","Madaripur", "Manikganj",
    "Munshiganj", "Narayanganj","Narsingdi","Rajbari","Shariatpur", "Tangail","Bagerhat", "Chuadanga","Jessore","Jhenaidaha","Khulna", "Kushtia",
    "Magura", "Meherpur","Narail","Satkhira","Jamalpur", "Mymensingh","Netrokona", "Sherpur","Bogura","Joypurhat","Naogan", "Natore",
    "Chapai Nawab Ganj", "Pabna","Rajshahi","Sirajganj","Dinajpur", "Gaibandha","Kurigram","Nilphamari","Lalmonirhaat","Panchagarh","Rangpur","Thakurgaon",
    "Habiganj","Moulovibajar", "Sunamganj","Sylhet"}));
    jPanel_accused.add(jComboBox_presentDistrict);
    jComboBox_presentDistrict.setBounds(290, 700, 550, 40);

    jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/logo.png"))); // NOI18N
    jPanel_accused.add(jLabel_logo);
    jLabel_logo.setBounds(990, 20, 210, 210);

    jLabel_background.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/bg_pic.jpg"))); // NOI18N
    jLabel_background.setText("jLabel1");
    jPanel_accused.add(jLabel_background);
    jLabel_background.setBounds(10, 10, 1250, 890);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_accused, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel_accused, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ageActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
          MainPage mObj = new MainPage();
        mObj.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        
        String query = "INSERT INTO Accused(CaseNo,AccusedName,Age,FathersName,Village,Thana,DistrictId,PresentAddress,PresentThana,PresentDistrictId) VALUES (?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst;
        try {
            pst = (PreparedStatement) cnObj.connection.prepareStatement(query);
            pst.setString(1,jTextField_caseId.getText());
            pst.setString(2,jTextField_name.getText());
            pst.setString(3,jTextField_age.getText());
            pst.setString(4,jTextField_fathersName.getText() );
            pst.setString(5,jTextField_village.getText() );
            pst.setString(6,jTextField4_thana.getText());
            
            String District = jComboBox_district.getSelectedItem().toString();
            if(District.equals("Barguna") )
            {
                pst.setString(7,"8001");
            }
            else if(District.equals("Barisal") )
            {
                pst.setString(7,"8002");
            }
            else if(District.equals("Bhola") )
            {
                pst.setString(7,"8003");
            }
            else if(District.equals("Jhalokathi") )
            {
                pst.setString(7,"8004");
            }
            else if(District.equals("Potuakhali") )
            {
                pst.setString(7,"8005");
            }
            else if(District.equals("Pirojpur") )
            {
                pst.setString(7,"8006");
            }
            else if(District.equals("Bandarban") )
            {
                pst.setString(7,"8007");
            }
            else if(District.equals("Brahmanbaria") )
            {
                pst.setString(7,"8008");
            }
            else if(District.equals("Chandpur") )
            {
                pst.setString(7,"8009");
            }
            else if(District.equals("Chittagong") )
            {
                pst.setString(7,"8010");
            }
            else if(District.equals("Comilla") )
            {
                pst.setString(7,"8011");
            }
            else if(District.equals("Coxs Bazar") )
            {
                pst.setString(7,"8012");
            }
            else if(District.equals("Feni") )
            {
                pst.setString(7,"8013");
            }
            else if(District.equals("Khagrachhari") )
            {
                pst.setString(7,"8014");
            }
            else if(District.equals("Lakshmipur") )
            {
                pst.setString(7,"8015");
            }
            else if(District.equals("Noakhali") )
            {
                pst.setString(7,"8016");
            }
            else if(District.equals("Rangamati") )
            {
                pst.setString(7,"8017");
            }
                else if(District.equals("Dhaka") )
            {
                pst.setString(7,"8018");
            }
            else if(District.equals("Faridpur") )
            {
                pst.setString(7,"8019");
            }
            else if(District.equals("Gazipur") )
            {
                pst.setString(7,"8020");
            }
            else if(District.equals("Gopalganj") )
            {
                pst.setString(7,"8021");
            }
                else if(District.equals("Kishorganj") )
            {
                pst.setString(7,"8022");
            }
            else if(District.equals("Madaripur") )
            {
                pst.setString(7,"8023");
            }
            else if(District.equals("Manikganj") )
            {
                pst.setString(7,"8024");
            }
            else if(District.equals("Munshiganj") )
            {
                pst.setString(7,"8025");
            }
            else if(District.equals("Narayanganj") )
            {
                pst.setString(7,"8026");
            }
            else if(District.equals("Narsingdi") )
            {
                pst.setString(7,"8027");
            }
            else if(District.equals("Rajbari") )
            {
                pst.setString(7,"8028");
            }
            else if(District.equals("Shariatpur") )
            {
                pst.setString(7,"8029");
            }
            else if(District.equals("Tangail") )
            {
                pst.setString(7,"8030");
            }
            else if(District.equals("Bagerhat") )
            {
                pst.setString(7,"8031");
            }
            else if(District.equals("Chuadanga") )
            {
                pst.setString(7,"8032");
            }
            else if(District.equals("Jessore") )
            {
                pst.setString(7,"8033");
            }
             else if(District.equals("Jhenaidaha") )
            {
                pst.setString(7,"8034");
            }
            else if(District.equals("Khulna") )
            {
                pst.setString(7,"8035");
            }
            else if(District.equals("Kushtia") )
            {
                pst.setString(7,"8036");
            }
            else if(District.equals("Magura") )
            {
                pst.setString(7,"8037");
            }
            else if(District.equals("Meherpur") )
            {
                pst.setString(7,"8038");
            }
            else if(District.equals("Narail") )
            {
                pst.setString(7,"8039");
            }
            else if(District.equals("Satkhira") )
            {
                pst.setString(7,"8040");
            }
            else if(District.equals("Jamalpur") )
            {
                pst.setString(7,"8041");
            }
            else if(District.equals("Mymensingh") )
            {
                pst.setString(7,"8042");
            }
            else if(District.equals("Netrokona") )
            {
                pst.setString(7,"8043");
            }
            else if(District.equals("Sherpur") )
            {
                pst.setString(7,"8044");
            }
            else if(District.equals("Bogura") )
            {
                pst.setString(7,"8045");
            }
            else if(District.equals("Joypurhat") )
            {
                pst.setString(7,"8046");
            }
            else if(District.equals("Naogan") )
            {
                pst.setString(7,"8047");
            }
            else if(District.equals("Natore") )
            {
                pst.setString(7,"8048");
            }
            else if(District.equals("Chapai Nawab Ganj") )
            {
                pst.setString(7,"8049");
            }
            else if(District.equals("Pabna") )
            {
                pst.setString(7,"8050");
            }
            else if(District.equals("Rajshahi") )
            {
                pst.setString(7,"8051");
            }
            else if(District.equals("Sirajganj") )
            {
                pst.setString(7,"8052");
            }
            else if(District.equals("Dinajpur") )
            {
                pst.setString(7,"8053");
            }
            else if(District.equals("Gaibandha") )
            {
                pst.setString(7,"8054");
            }
            else if(District.equals("Kurigram") )
            {
                pst.setString(7,"8055");
            }
            else if(District.equals("Nilphamari") )
            {
                pst.setString(7,"8056");
            }
            else if(District.equals("Lalmonirhaat") )
            {
                pst.setString(7,"8057");
            }
            else if(District.equals("Panchagarh") )
            {
                pst.setString(7,"8058");
            }
            else if(District.equals("Rangpur") )
            {
                pst.setString(7,"8059");
            }
            else if(District.equals("Thakurgaon") )
            {
                pst.setString(7,"8060");
            }
            else if(District.equals("Habiganj") )
            {
                pst.setString(7,"8061");
            }
            else if(District.equals("Moulovibajar") )
            {
                pst.setString(7,"8062");
            }
            else if(District.equals("Sunamganj") )
            {
                pst.setString(7,"8063");
            }
            else if(District.equals("Sylhet") )
            {
                pst.setString(7,"8064");
            }
          
            
            pst.setString(8,jTextField_presentAddress.getText());
            pst.setString(9,jTextField_presentThana.getText());
            String pDistrict = jComboBox_presentDistrict.getSelectedItem().toString();
            if(pDistrict.equals("Barguna") )
            {
                pst.setString(10,"8001");
            }
            else if(pDistrict.equals("Barisal") )
            {
                pst.setString(10,"8002");
            }
            else if(pDistrict.equals("Bhola") )
            {
                pst.setString(10,"8003");
            }
            else if(pDistrict.equals("Jhalokathi") )
            {
                pst.setString(10,"8004");
            }
            else if(pDistrict.equals("Potuakhali") )
            {
                pst.setString(10,"8005");
            }
            else if(pDistrict.equals("Pirojpur") )
            {
                pst.setString(10,"8006");
            }
            else if(pDistrict.equals("Bandarban") )
            {
                pst.setString(10,"8007");
            }
            else if(pDistrict.equals("Brahmanbaria") )
            {
                pst.setString(10,"8008");
            }
            else if(pDistrict.equals("Chandpur") )
            {
                pst.setString(10,"8009");
            }
            else if(pDistrict.equals("Chittagong") )
            {
                pst.setString(10,"8010");
            }
            else if(pDistrict.equals("Comilla") )
            {
                pst.setString(10,"8011");
            }
            else if(pDistrict.equals("Coxs Bazar") )
            {
                pst.setString(10,"8012");
            }
            else if(pDistrict.equals("Feni") )
            {
                pst.setString(10,"8013");
            }
            else if(pDistrict.equals("Khagrachhari") )
            {
                pst.setString(10,"8014");
            }
            else if(pDistrict.equals("Lakshmipur") )
            {
                pst.setString(10,"8015");
            }
            else if(pDistrict.equals("Noakhali") )
            {
                pst.setString(10,"8016");
            }
            else if(pDistrict.equals("Rangamati") )
            {
                pst.setString(10,"8017");
            }
            else if(pDistrict.equals("Dhaka") )
            {
                pst.setString(10,"8018");
            }
            else if(pDistrict.equals("Faridpur") )
            {
                pst.setString(10,"8019");
            }
            else if(pDistrict.equals("Gazipur") )
            {
                pst.setString(10,"8020");
            }
            else if(pDistrict.equals("Gopalganj") )
            {
                pst.setString(10,"8021");
            }
            else if(pDistrict.equals("Kishorganj") )
            {
                pst.setString(10,"8022");
            }
            else if(pDistrict.equals("Madaripur") )
            {
                pst.setString(10,"8023");
            }
            else if(pDistrict.equals("Manikganj") )
            {
                pst.setString(10,"8024");
            }
            else if(pDistrict.equals("Munshiganj") )
            {
                pst.setString(10,"8025");
            }
            else if(pDistrict.equals("Narayanganj") )
            {
                pst.setString(10,"8026");
            }
            else if(pDistrict.equals("Narsingdi") )
            {
                pst.setString(10,"8027");
            }
            else if(pDistrict.equals("Rajbari") )
            {
                pst.setString(10,"8028");
            }
            else if(pDistrict.equals("Shariatpur") )
            {
                pst.setString(10,"8029");
            }
            else if(pDistrict.equals("Tangail") )
            {
                pst.setString(10,"8030");
            }
            else if(pDistrict.equals("Bagerhat") )
            {
                pst.setString(10,"8031");
            }
            else if(pDistrict.equals("Chuadanga") )
            {
                pst.setString(10,"8032");
            }
            else if(pDistrict.equals("Jessore") )
            {
                pst.setString(10,"8033");
            }
            else if(pDistrict.equals("Jhenaidaha") )
            {
                pst.setString(10,"8034");
            }
            else if(pDistrict.equals("Khulna") )
            {
                pst.setString(10,"8035");
            }
            else if(pDistrict.equals("Kushtia") )
            {
                pst.setString(10,"8036");
            }
            else if(pDistrict.equals("Magura") )
            {
                pst.setString(10,"8037");
            }
            else if(pDistrict.equals("Meherpur") )
            {
                pst.setString(10,"8038");
            }
            else if(pDistrict.equals("Narail") )
            {
                pst.setString(10,"8039");
            }
            else if(pDistrict.equals("Satkhira") )
            {
                pst.setString(10,"8040");
            }
            else if(pDistrict.equals("Jamalpur") )
            {
                pst.setString(10,"8041");
            }
            else if(pDistrict.equals("Mymensingh") )
            {
                pst.setString(10,"8042");
            }
            else if(pDistrict.equals("Netrokona") )
            {
                pst.setString(10,"8043");
            }
            else if(pDistrict.equals("Sherpur") )
            {
                pst.setString(10,"8044");
            }
            else if(pDistrict.equals("Bogura") )
            {
                pst.setString(10,"8045");
            }
            else if(pDistrict.equals("Joypurhat") )
            {
                pst.setString(10,"8046");
            }
            else if(pDistrict.equals("Naogan") )
            {
                pst.setString(10,"8047");
            }
            else if(pDistrict.equals("Natore") )
            {
                pst.setString(10,"8048");
            }
            else if(pDistrict.equals("Chapai Nawab Ganj") )
            {
                pst.setString(10,"8049");
            }
            else if(pDistrict.equals("Pabna") )
            {
                pst.setString(10,"8050");
            }
            else if(pDistrict.equals("Rajshahi") )
            {
                pst.setString(10,"8051");
            }
            else if(pDistrict.equals("Sirajganj") )
            {
                pst.setString(10,"8052");
            }
            else if(pDistrict.equals("Dinajpur") )
            {
                pst.setString(10,"8053");
            }
            else if(pDistrict.equals("Gaibandha") )
            {
                pst.setString(10,"8054");
            }
            else if(pDistrict.equals("Kurigram") )
            {
                pst.setString(10,"8055");
            }
            else if(pDistrict.equals("Nilphamari") )
            {
                pst.setString(10,"8056");
            }
            else if(pDistrict.equals("Lalmonirhaat") )
            {
                pst.setString(10,"8057");
            }
            else if(pDistrict.equals("Panchagarh") )
            {
                pst.setString(10,"8058");
            }
            else if(pDistrict.equals("Rangpur") )
            {
                pst.setString(10,"8059");
            }
            else if(pDistrict.equals("Thakurgaon") )
            {
                pst.setString(10,"8060");
            }
            else if(pDistrict.equals("Habiganj") )
            {
                pst.setString(10,"8061");
            }
            else if(pDistrict.equals("Moulovibajar") )
            {
                pst.setString(10,"8062");
            }
            else if(pDistrict.equals("Sunamganj") )
            {
                pst.setString(10,"8063");
            }
            else if(pDistrict.equals("Sylhet") )
            {
                pst.setString(10,"8064");
            }
            
            
           if(jTextField_caseId.getText().equals("")){
               JOptionPane.showMessageDialog(null,"Please fill up the required(*) text fields!!");
           }else{
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted SUCCESSFULLY");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(VictimPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccusedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccusedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccusedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccusedJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccusedJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_save;
    private javax.swing.JComboBox<String> jComboBox_district;
    private javax.swing.JComboBox<String> jComboBox_presentDistrict;
    private javax.swing.JLabel jLabel_AccusedName;
    private javax.swing.JLabel jLabel_District;
    private javax.swing.JLabel jLabel_PresentAdress;
    private javax.swing.JLabel jLabel_PresentDistrict;
    private javax.swing.JLabel jLabel_PresentDistrict1;
    private javax.swing.JLabel jLabel_PresentThana;
    private javax.swing.JLabel jLabel_Thana;
    private javax.swing.JLabel jLabel_Village;
    private javax.swing.JLabel jLabel_accused;
    private javax.swing.JLabel jLabel_age;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_fathersName;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel_accused;
    private javax.swing.JTextField jTextField4_thana;
    private javax.swing.JTextField jTextField_age;
    private javax.swing.JTextField jTextField_caseId;
    private javax.swing.JTextField jTextField_fathersName;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_presentAddress;
    private javax.swing.JTextField jTextField_presentThana;
    private javax.swing.JTextField jTextField_village;
    // End of variables declaration//GEN-END:variables
}
