

package PoliceStationManagement;
import SQLPackage.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PoliceOfficerUpdate extends javax.swing.JFrame {

    /** Creates new form PoliceOfficerPage */
    public PoliceOfficerUpdate() {
        initComponents();
        setTitle("Police Officer");
        setSize(1250,885);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OfficerNameTextField = new javax.swing.JTextField();
        DesignationTextField = new javax.swing.JTextField();
        OfficerAreaTextField = new javax.swing.JTextField();
        CaseHandledTextField = new javax.swing.JTextField();
        OfficerPhoneTextField = new javax.swing.JTextField();
        OfficerAddressTextField = new javax.swing.JTextField();
        DutyhrTextField = new javax.swing.JTextField();
        ExperienceTextField = new javax.swing.JTextField();
        OfficerBackButton = new javax.swing.JButton();
        OfficerUpdateButton = new javax.swing.JButton();
        caseHandledLabel = new javax.swing.JLabel();
        ExperienceLabel = new javax.swing.JLabel();
        DutyHrLabel = new javax.swing.JLabel();
        OfficerAddressLabel = new javax.swing.JLabel();
        OfficerPhoneLabel = new javax.swing.JLabel();
        DesignationLabel = new javax.swing.JLabel();
        OfficerAreaLabel = new javax.swing.JLabel();
        OfficerNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();
        Bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        OfficerNameTextField.setEditable(false);
        OfficerNameTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(OfficerNameTextField);
        OfficerNameTextField.setBounds(360, 90, 640, 40);

        DesignationTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(DesignationTextField);
        DesignationTextField.setBounds(360, 170, 640, 40);

        OfficerAreaTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(OfficerAreaTextField);
        OfficerAreaTextField.setBounds(360, 240, 640, 40);

        CaseHandledTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(CaseHandledTextField);
        CaseHandledTextField.setBounds(360, 310, 640, 40);

        OfficerPhoneTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(OfficerPhoneTextField);
        OfficerPhoneTextField.setBounds(360, 380, 640, 40);

        OfficerAddressTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(OfficerAddressTextField);
        OfficerAddressTextField.setBounds(360, 460, 640, 40);

        DutyhrTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DutyhrTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DutyhrTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DutyhrTextField);
        DutyhrTextField.setBounds(360, 540, 640, 40);

        ExperienceTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(ExperienceTextField);
        ExperienceTextField.setBounds(360, 620, 650, 40);

        OfficerBackButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OfficerBackButton.setText("BACK");
        OfficerBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficerBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OfficerBackButton);
        OfficerBackButton.setBounds(30, 690, 170, 50);

        OfficerUpdateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OfficerUpdateButton.setText("UPDATE");
        OfficerUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficerUpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OfficerUpdateButton);
        OfficerUpdateButton.setBounds(1020, 690, 180, 50);

        caseHandledLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        caseHandledLabel.setForeground(new java.awt.Color(240, 240, 240));
        caseHandledLabel.setText("Total Case Handled       : ");
        getContentPane().add(caseHandledLabel);
        caseHandledLabel.setBounds(80, 310, 260, 25);

        ExperienceLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        ExperienceLabel.setForeground(new java.awt.Color(240, 240, 240));
        ExperienceLabel.setText("Years of Experience      : ");
        getContentPane().add(ExperienceLabel);
        ExperienceLabel.setBounds(80, 630, 260, 25);

        DutyHrLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        DutyHrLabel.setForeground(new java.awt.Color(240, 240, 240));
        DutyHrLabel.setText("Duty Hour                     : ");
        getContentPane().add(DutyHrLabel);
        DutyHrLabel.setBounds(80, 550, 260, 25);

        OfficerAddressLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        OfficerAddressLabel.setForeground(new java.awt.Color(240, 240, 240));
        OfficerAddressLabel.setText("Address                          : ");
        getContentPane().add(OfficerAddressLabel);
        OfficerAddressLabel.setBounds(80, 470, 260, 25);

        OfficerPhoneLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        OfficerPhoneLabel.setForeground(new java.awt.Color(240, 240, 240));
        OfficerPhoneLabel.setText("Phone No*                     : ");
        getContentPane().add(OfficerPhoneLabel);
        OfficerPhoneLabel.setBounds(80, 390, 260, 25);

        DesignationLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        DesignationLabel.setForeground(new java.awt.Color(240, 240, 240));
        DesignationLabel.setText("Designation*                  : ");
        getContentPane().add(DesignationLabel);
        DesignationLabel.setBounds(80, 170, 260, 25);

        OfficerAreaLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        OfficerAreaLabel.setForeground(new java.awt.Color(240, 240, 240));
        OfficerAreaLabel.setText("Area*                              : ");
        getContentPane().add(OfficerAreaLabel);
        OfficerAreaLabel.setBounds(80, 240, 270, 25);

        OfficerNameLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        OfficerNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        OfficerNameLabel.setText("Police Officer Name*    : ");
        getContentPane().add(OfficerNameLabel);
        OfficerNameLabel.setBounds(80, 100, 270, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Police Officer Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 20, 480, 58);

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/logo.png"))); // NOI18N
        logo_label.setText("jLabel2");
        getContentPane().add(logo_label);
        logo_label.setBounds(1030, 20, 210, 210);

        Bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/bg_pic.jpg"))); // NOI18N
        Bg_label.setText("jLabel1");
        Bg_label.setMaximumSize(new java.awt.Dimension(1250, 885));
        Bg_label.setMinimumSize(new java.awt.Dimension(1250, 885));
        Bg_label.setPreferredSize(new java.awt.Dimension(1250, 885));
        getContentPane().add(Bg_label);
        Bg_label.setBounds(0, 0, 1250, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OfficerUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficerUpdateButtonActionPerformed
        // TODO add your handling code here:
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();

        String pol_name=OfficerNameTextField.getText();
        String pol_desig=DesignationTextField.getText();
        String pol_area=OfficerAreaTextField.getText() ;
        String pol_casehandld=CaseHandledTextField.getText() ;
        String pol_phn=OfficerPhoneTextField.getText();
        String pol_add=OfficerAddressTextField.getText();
        int pol_dutyhr=Integer.parseInt(DutyhrTextField.getText());
        int pol_exp=Integer.parseInt(ExperienceTextField.getText());
        
        String updatequery= "UPDATE PoliceOfficer SET PoliceOfficerName='"+pol_name+"',Designation='"+pol_desig+"',Area='"+pol_area+"',CaseHandledNo='"+pol_casehandld+"',PhoneNo='"+pol_phn+"',Address='"+pol_add+"',DutyHour='"+pol_dutyhr+"', YearsOfExperience='"+pol_exp+"' WHERE PoliceOfficerName='"+pol_name+"'";    
            try {
            
            Statement st = (Statement) cnObj.connection.createStatement();
            st.executeUpdate(updatequery);
            JOptionPane.showMessageDialog(null,"Updated SUCCESSFULLY");
        } catch (SQLException ex) {
            Logger.getLogger(AccusedUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
           
        
    }//GEN-LAST:event_OfficerUpdateButtonActionPerformed

    private void OfficerBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficerBackButtonActionPerformed
        // TODO add your handling code here:
        MainPage mObj = new MainPage();
        mObj.show();
        this.setVisible(false);
    }//GEN-LAST:event_OfficerBackButtonActionPerformed

    private void DutyhrTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DutyhrTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DutyhrTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceOfficerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceOfficerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceOfficerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceOfficerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceOfficerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg_label;
    public javax.swing.JTextField CaseHandledTextField;
    private javax.swing.JLabel DesignationLabel;
    public javax.swing.JTextField DesignationTextField;
    private javax.swing.JLabel DutyHrLabel;
    public javax.swing.JTextField DutyhrTextField;
    private javax.swing.JLabel ExperienceLabel;
    public javax.swing.JTextField ExperienceTextField;
    private javax.swing.JLabel OfficerAddressLabel;
    public javax.swing.JTextField OfficerAddressTextField;
    private javax.swing.JLabel OfficerAreaLabel;
    public javax.swing.JTextField OfficerAreaTextField;
    private javax.swing.JButton OfficerBackButton;
    private javax.swing.JLabel OfficerNameLabel;
    public javax.swing.JTextField OfficerNameTextField;
    private javax.swing.JLabel OfficerPhoneLabel;
    public javax.swing.JTextField OfficerPhoneTextField;
    private javax.swing.JButton OfficerUpdateButton;
    private javax.swing.JLabel caseHandledLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo_label;
    // End of variables declaration//GEN-END:variables

}
