
package PoliceStationManagement;
import SQLPackage.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PoliceStationForm extends javax.swing.JFrame {

    /**
     * Creates new form PoliceStationForm
     */
    public PoliceStationForm() {
        initComponents();
        setSize(1250,885);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        PoliceStationName = new javax.swing.JLabel();
        PoliceStationNameTextfield = new javax.swing.JTextField();
        CodeNo = new javax.swing.JLabel();
        CodeNoTextField = new javax.swing.JTextField();
        Area = new javax.swing.JLabel();
        AreaTextField = new javax.swing.JTextField();
        OfficerInCharge = new javax.swing.JLabel();
        OfficerInChargeTextField = new javax.swing.JTextField();
        BackButtonPSF = new javax.swing.JButton();
        SaveButtonPSF = new javax.swing.JButton();
        policeStationForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(null);

        PoliceStationName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PoliceStationName.setForeground(new java.awt.Color(255, 255, 255));
        PoliceStationName.setText("Police Station Name *");
        PoliceStationName.setToolTipText("");
        panel1.add(PoliceStationName);
        PoliceStationName.setBounds(80, 220, 270, 30);
        panel1.add(PoliceStationNameTextfield);
        PoliceStationNameTextfield.setBounds(370, 220, 460, 30);

        CodeNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CodeNo.setForeground(new java.awt.Color(255, 255, 255));
        CodeNo.setText("Code No *");
        panel1.add(CodeNo);
        CodeNo.setBounds(80, 300, 230, 30);
        panel1.add(CodeNoTextField);
        CodeNoTextField.setBounds(370, 310, 460, 30);

        Area.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Area.setForeground(new java.awt.Color(255, 255, 255));
        Area.setText("Area *");
        panel1.add(Area);
        Area.setBounds(80, 390, 130, 29);
        panel1.add(AreaTextField);
        AreaTextField.setBounds(370, 390, 460, 30);

        OfficerInCharge.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        OfficerInCharge.setForeground(new java.awt.Color(255, 255, 255));
        OfficerInCharge.setText("Officer In Charge");
        panel1.add(OfficerInCharge);
        OfficerInCharge.setBounds(80, 440, 205, 80);
        panel1.add(OfficerInChargeTextField);
        OfficerInChargeTextField.setBounds(370, 470, 460, 30);

        BackButtonPSF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackButtonPSF.setText("BACK");
        BackButtonPSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonPSFActionPerformed(evt);
            }
        });
        panel1.add(BackButtonPSF);
        BackButtonPSF.setBounds(80, 640, 150, 40);

        SaveButtonPSF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveButtonPSF.setText("SAVE");
        SaveButtonPSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonPSFActionPerformed(evt);
            }
        });
        panel1.add(SaveButtonPSF);
        SaveButtonPSF.setBounds(980, 640, 160, 40);

        policeStationForm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        policeStationForm.setForeground(new java.awt.Color(255, 255, 255));
        policeStationForm.setText("Police Station Form");
        panel1.add(policeStationForm);
        policeStationForm.setBounds(440, 100, 380, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Enter the following details:");
        panel1.add(jLabel1);
        jLabel1.setBounds(80, 160, 390, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/logo.png"))); // NOI18N
        panel1.add(logo);
        logo.setBounds(1030, 10, 210, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/policeStation.jpg"))); // NOI18N
        panel1.add(jLabel2);
        jLabel2.setBounds(0, -70, 2000, 940);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 799, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonPSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonPSFActionPerformed
        // TODO add your handling code here:
          MainPage mObj = new MainPage();
        mObj.show();
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonPSFActionPerformed

    private void SaveButtonPSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonPSFActionPerformed
         ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        
        String query = "INSERT INTO PoliceStation(PoliceStationName,CodeNo,Area,OfficerInCharge) VALUES (?,?,?,?)";
        PreparedStatement pst;
        try {
            pst = (PreparedStatement) cnObj.connection.prepareStatement(query);
            pst.setString(1,PoliceStationNameTextfield.getText());
            pst.setString(2,CodeNoTextField.getText());
            pst.setString(3,AreaTextField.getText() );
            pst.setString(4,OfficerInChargeTextField.getText() );
         
   
        
            if((PoliceStationNameTextfield.getText().equals("")) || (CodeNoTextField.getText().equals(""))|| (AreaTextField.getText().equals("")) ){
                JOptionPane.showMessageDialog(null,"Please fill up the required(*) text fields!!");
            }
            else{
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Inserted SUCCESSFULLY");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VictimPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                                        
    }//GEN-LAST:event_SaveButtonPSFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceStationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceStationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area;
    private javax.swing.JTextField AreaTextField;
    private javax.swing.JButton BackButtonPSF;
    private javax.swing.JLabel CodeNo;
    private javax.swing.JTextField CodeNoTextField;
    private javax.swing.JLabel OfficerInCharge;
    private javax.swing.JTextField OfficerInChargeTextField;
    private javax.swing.JLabel PoliceStationName;
    private javax.swing.JTextField PoliceStationNameTextfield;
    private javax.swing.JButton SaveButtonPSF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logo;
    private java.awt.Panel panel1;
    private javax.swing.JLabel policeStationForm;
    // End of variables declaration//GEN-END:variables
}
