/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PoliceStationManagement;

import SQLPackage.ConnectMSSQL;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        setSize(1250,885);
        Font font = new Font("Tahoma", Font.PLAIN, 20);
     /*   this.RecievingDateTable.setFont(font);
        int gap = 15;
        this.RecievingDateTable.setRowHeight(this.RecievingDateTable.getRowHeight()+gap);
        
        this.caseClosedTable.setFont(font);        
        this.caseClosedTable.setRowHeight(this.caseClosedTable.getRowHeight()+gap);
        
        this.AccusedNameTable.setFont(font);    
        this.AccusedNameTable.setRowHeight(this.AccusedNameTable.getRowHeight()+gap);*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalCaseTextField = new javax.swing.JTextField();
        TotalCaseButton = new javax.swing.JButton();
        TotalCaseCombobox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        MaxOfficerCaseTextField = new javax.swing.JTextField();
        MaxOfficerDesignationTextField = new javax.swing.JTextField();
        MaxOfficerNameTextField = new javax.swing.JTextField();
        MaxOfficerCaseButton = new javax.swing.JButton();
        toComboBox = new javax.swing.JComboBox<>();
        fromComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecievingDateTable = new javax.swing.JTable();
        ReceivedCasesButton = new javax.swing.JButton();
        caseClosedButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        caseClosedTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        phoneNoButton = new javax.swing.JButton();
        caseNoTextField = new javax.swing.JTextField();
        phoneNoTextField = new javax.swing.JTextField();
        AccusedNameButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AccusedNameTable = new javax.swing.JTable();
        caseClosedButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        totalCaseTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(totalCaseTextField);
        totalCaseTextField.setBounds(700, 240, 190, 40);

        TotalCaseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalCaseButton.setText("SHOW");
        TotalCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCaseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TotalCaseButton);
        TotalCaseButton.setBounds(540, 240, 100, 40);

        TotalCaseCombobox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalCaseCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECt--", "GD", "FIR" }));
        getContentPane().add(TotalCaseCombobox);
        TotalCaseCombobox.setBounds(334, 240, 150, 40);

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("CaseNo");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1151, 340, 60, 16);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Designation");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(990, 340, 90, 16);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(840, 340, 51, 16);

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(70, 750, 130, 40);

        MaxOfficerCaseTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(MaxOfficerCaseTextField);
        MaxOfficerCaseTextField.setBounds(1150, 360, 60, 40);

        MaxOfficerDesignationTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(MaxOfficerDesignationTextField);
        MaxOfficerDesignationTextField.setBounds(940, 360, 200, 40);

        MaxOfficerNameTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(MaxOfficerNameTextField);
        MaxOfficerNameTextField.setBounds(790, 360, 140, 40);

        MaxOfficerCaseButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MaxOfficerCaseButton.setText("SHOW");
        MaxOfficerCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxOfficerCaseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MaxOfficerCaseButton);
        MaxOfficerCaseButton.setBounds(660, 360, 110, 40);

        toComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        toComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "2018-06-03", "2018-11-06", "2018-12-15", "2019-01-03", "2019-02-20", "2019-02-28" }));
        getContentPane().add(toComboBox);
        toComboBox.setBounds(670, 430, 120, 30);

        fromComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "2018-01-06", "2018-06-03", "2018-11-06", "2018-12-15", "2019-01-03", "2019-02-20" }));
        getContentPane().add(fromComboBox);
        fromComboBox.setBounds(490, 430, 130, 30);

        RecievingDateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receiving Date", "Total Cases"
            }
        ));
        jScrollPane1.setViewportView(RecievingDateTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(930, 420, 260, 70);

        ReceivedCasesButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ReceivedCasesButton.setText("SHOW");
        ReceivedCasesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceivedCasesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReceivedCasesButton);
        ReceivedCasesButton.setBounds(810, 430, 91, 30);

        caseClosedButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        caseClosedButton.setText("SHOW");
        caseClosedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseClosedButtonActionPerformed(evt);
            }
        });
        getContentPane().add(caseClosedButton);
        caseClosedButton.setBounds(820, 510, 91, 31);

        caseClosedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CaseNo", "Criminal Status"
            }
        ));
        jScrollPane3.setViewportView(caseClosedTable);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(930, 500, 260, 90);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("-> Show Cases and Criminal status which are not closed yet ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(90, 510, 740, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("To");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 440, 60, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("-> Show count of cases between ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 430, 400, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("-> Police Officer who handled maximum cases ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 360, 570, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("->AccusedName who have more than 1 cases");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 620, 590, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-> Total Cases of");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 240, 230, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("-> Enter phone no to search ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(90, 310, 400, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPORT:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 100, 240, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(990, 20, 210, 210);

        phoneNoButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoneNoButton.setText("SHOW");
        phoneNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNoButton);
        phoneNoButton.setBounds(650, 310, 100, 30);

        caseNoTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        caseNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(caseNoTextField);
        caseNoTextField.setBounds(780, 310, 170, 30);

        phoneNoTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(phoneNoTextField);
        phoneNoTextField.setBounds(440, 310, 170, 40);

        AccusedNameButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AccusedNameButton.setText("SHOW");
        AccusedNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccusedNameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AccusedNameButton);
        AccusedNameButton.setBounds(670, 630, 100, 30);

        AccusedNameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AccusedName"
            }
        ));
        jScrollPane2.setViewportView(AccusedNameTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(930, 610, 260, 100);

        caseClosedButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        caseClosedButton1.setText("SHOW");
        caseClosedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseClosedButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(caseClosedButton1);
        caseClosedButton1.setBounds(820, 510, 91, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/bg_pic.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 1250, 900);

        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 320, 48, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalCaseButtonActionPerformed
        // TODO add your handling code here:
        String typeofcase=TotalCaseCombobox.getSelectedItem().toString();
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        
            
            String query = "select count(TypeOfCase) from cases where TypeofCase='"+typeofcase+"' ";
            Statement st;
            try {
            st = cnObj.connection.createStatement();
            ResultSet rs= st.executeQuery(query);
            while(rs.next()){
                String count = rs.getString("");
                totalCaseTextField.setText(count);
                
            }
            } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
            }
       
            
    }//GEN-LAST:event_TotalCaseButtonActionPerformed

    private void MaxOfficerCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxOfficerCaseButtonActionPerformed
        // TODO add your handling code here:
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        String query = "select Top 1 PoliceOfficerName,Designation,max(CaseHandledNo) from PoliceOfficer  group by PoliceOfficerName,Designation ";
        Statement st;
        try {
            st = cnObj.connection.createStatement();
            ResultSet rs= st.executeQuery(query);
            while(rs.next()){
                String name = rs.getString("PoliceOfficerName");
                MaxOfficerNameTextField.setText(name);
                String desig = rs.getString("Designation");
                MaxOfficerDesignationTextField.setText(desig);
                String count = rs.getString("");
                MaxOfficerCaseTextField.setText(count);
                
        }
            
           // int i=rs.getInt("count(TypeOfCase)");
           // totalCaseTextField.setText(String.valueOf(i));
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MaxOfficerCaseButtonActionPerformed

    private void ReceivedCasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceivedCasesButtonActionPerformed
        // TODO add your handling code here:
        String from = fromComboBox.getSelectedItem().toString();
        String to = toComboBox.getSelectedItem().toString();
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        String query = "Select ReceivingDate,count(CaseNo) from cases where ReceivingDate BETWEEN '"+from+"' AND '"+to+"' group by ReceivingDate";
        Statement st;
        try {
            st = cnObj.connection.createStatement();
            ResultSet rs= st.executeQuery(query);
            DefaultTableModel Model= (DefaultTableModel)RecievingDateTable.getModel();
            Object[] row= new Object[11];
            while(rs.next()){
               row[0] = rs.getString("ReceivingDate");
               row[1] = rs.getString("");
               Model.addRow(row);
                
            }
            
           // int i=rs.getInt("count(TypeOfCase)");
           // totalCaseTextField.setText(String.valueOf(i));
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ReceivedCasesButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
         MainPage mObj = new MainPage();
        mObj.show();
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void caseClosedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseClosedButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseClosedButton1ActionPerformed

    private void caseClosedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseClosedButtonActionPerformed
        // TODO add your handling code here:
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        String query = "select CaseNo,CriminalStatus from cases where ClosingDate<> ''";
        Statement st;
        try {
            st = cnObj.connection.createStatement();
            ResultSet rs= st.executeQuery(query);
            DefaultTableModel Model= (DefaultTableModel)caseClosedTable.getModel();
            Object[] row= new Object[11];
            Model.setRowCount(0);
            while(rs.next()){
                row[0] = rs.getInt("CaseNo");
                row[1] = rs.getString("CriminalStatus");
                Model.addRow(row);

            }

            // int i=rs.getInt("count(TypeOfCase)");
            // totalCaseTextField.setText(String.valueOf(i));
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_caseClosedButtonActionPerformed

    private void AccusedNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccusedNameButtonActionPerformed
        // TODO add your handling code here:
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        String query = "Select AccusedName from accused group by AccusedName having count(distinct CaseNo)  >1 ";
        Statement st;
        try {
            st = cnObj.connection.createStatement();
            ResultSet rs= st.executeQuery(query);
            DefaultTableModel Model= (DefaultTableModel)AccusedNameTable.getModel();
            Object[] row= new Object[11];
            Model.setRowCount(0);
            while(rs.next()){              
                row[0] = rs.getString("AccusedName");
                Model.addRow(row);

            }

            // int i=rs.getInt("count(TypeOfCase)");
            // totalCaseTextField.setText(String.valueOf(i));
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AccusedNameButtonActionPerformed

    private void phoneNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoButtonActionPerformed
        // TODO add your handling code here:
        String phoneNo = phoneNoTextField.getText();
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        String query = "select CaseNo from cases where \n" +
                        "CaseNo =(select CaseNo from Victim where  MobileNo='"+phoneNo+"')\n" +
                        "or\n" +
                        "CaseNo in (select CaseNo from PoliceOfficer where  PhoneNo='"+phoneNo+"')\n" +
                        "or\n" +
                        "CaseNo in(select CaseNo from Witness where  MobileNo='"+phoneNo+"'); ";
        Statement st;
        try {
            st = cnObj.connection.createStatement();
            ResultSet rs= st.executeQuery(query);
            while(rs.next()){              
                caseNoTextField.setText(rs.getString("CaseNo"));

            }

            // int i=rs.getInt("count(TypeOfCase)");
            // totalCaseTextField.setText(String.valueOf(i));
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_phoneNoButtonActionPerformed

    private void caseNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseNoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccusedNameButton;
    private javax.swing.JTable AccusedNameTable;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton MaxOfficerCaseButton;
    private javax.swing.JTextField MaxOfficerCaseTextField;
    private javax.swing.JTextField MaxOfficerDesignationTextField;
    private javax.swing.JTextField MaxOfficerNameTextField;
    private javax.swing.JButton ReceivedCasesButton;
    private javax.swing.JTable RecievingDateTable;
    private javax.swing.JButton TotalCaseButton;
    private javax.swing.JComboBox<String> TotalCaseCombobox;
    private javax.swing.JButton caseClosedButton;
    private javax.swing.JButton caseClosedButton1;
    private javax.swing.JTable caseClosedTable;
    private javax.swing.JTextField caseNoTextField;
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton phoneNoButton;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JComboBox<String> toComboBox;
    private javax.swing.JTextField totalCaseTextField;
    // End of variables declaration//GEN-END:variables
}
