package PoliceStationManagement;
import SQLPackage.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class VictimUpdate extends javax.swing.JFrame {

    /**
     * Creates new form VictimPage
     */
    public VictimUpdate() {
        initComponents();
        setSize(1250,885);
        setTitle("Victim");
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VictimNameLabel1 = new javax.swing.JLabel();
        VictimCaseIdTextField = new javax.swing.JTextField();
        VictimPresentDistrictLabel1 = new javax.swing.JLabel();
        VictimMobileNoTextField = new javax.swing.JTextField();
        VictimPresentAddressTextField = new javax.swing.JTextField();
        VictimSubmitButton = new javax.swing.JButton();
        VictimbackButton = new javax.swing.JButton();
        VictimPresentThanaTextField = new javax.swing.JTextField();
        VictimThanaTextField = new javax.swing.JTextField();
        VictimVillageTextField = new javax.swing.JTextField();
        VictimFatherTextField = new javax.swing.JTextField();
        VictimAgeTextField = new javax.swing.JTextField();
        VictimNameTextField = new javax.swing.JTextField();
        VictimformLabel = new javax.swing.JLabel();
        VictimPresentDistrictLabel = new javax.swing.JLabel();
        VictimPresentThanaLabel = new javax.swing.JLabel();
        VictimPresentAddressLabel = new javax.swing.JLabel();
        VictimDistrictLabel = new javax.swing.JLabel();
        VictimThanaLabel = new javax.swing.JLabel();
        VictimVillageLabel = new javax.swing.JLabel();
        VictimFatherLabel = new javax.swing.JLabel();
        VictimAgeLabel = new javax.swing.JLabel();
        VictimNameLabel = new javax.swing.JLabel();
        VictimDistrictComboBox = new javax.swing.JComboBox<>();
        VictimPresentDistrictComboBox = new javax.swing.JComboBox<>();
        logo_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 885));
        getContentPane().setLayout(null);

        VictimNameLabel1.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        VictimNameLabel1.setText("Case No*     :");
        getContentPane().add(VictimNameLabel1);
        VictimNameLabel1.setBounds(80, 110, 190, 30);

        VictimCaseIdTextField.setEditable(false);
        VictimCaseIdTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimCaseIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimCaseIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimCaseIdTextField);
        VictimCaseIdTextField.setBounds(300, 110, 680, 40);

        VictimPresentDistrictLabel1.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentDistrictLabel1.setForeground(new java.awt.Color(240, 240, 240));
        VictimPresentDistrictLabel1.setText("Mobile No*  : ");
        getContentPane().add(VictimPresentDistrictLabel1);
        VictimPresentDistrictLabel1.setBounds(80, 710, 190, 25);

        VictimMobileNoTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimMobileNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimMobileNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimMobileNoTextField);
        VictimMobileNoTextField.setBounds(300, 710, 680, 40);

        VictimPresentAddressTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimPresentAddressTextField);
        VictimPresentAddressTextField.setBounds(300, 530, 680, 40);

        VictimSubmitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimSubmitButton.setText("Submit");
        VictimSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimSubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VictimSubmitButton);
        VictimSubmitButton.setBounds(1000, 770, 200, 50);

        VictimbackButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimbackButton.setText("Back");
        VictimbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimbackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VictimbackButton);
        VictimbackButton.setBounds(80, 770, 180, 50);

        VictimPresentThanaTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimPresentThanaTextField);
        VictimPresentThanaTextField.setBounds(300, 590, 680, 40);

        VictimThanaTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimThanaTextField);
        VictimThanaTextField.setBounds(300, 410, 680, 40);

        VictimVillageTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimVillageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimVillageTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimVillageTextField);
        VictimVillageTextField.setBounds(300, 350, 680, 40);

        VictimFatherTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimFatherTextField);
        VictimFatherTextField.setBounds(300, 290, 680, 40);

        VictimAgeTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimAgeTextField);
        VictimAgeTextField.setBounds(300, 230, 680, 40);

        VictimNameTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimNameTextField);
        VictimNameTextField.setBounds(300, 170, 680, 40);

        VictimformLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        VictimformLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimformLabel.setText("Victim Form");
        getContentPane().add(VictimformLabel);
        VictimformLabel.setBounds(470, 30, 310, 60);

        VictimPresentDistrictLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentDistrictLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimPresentDistrictLabel.setText("Present District  : ");
        getContentPane().add(VictimPresentDistrictLabel);
        VictimPresentDistrictLabel.setBounds(80, 650, 190, 25);

        VictimPresentThanaLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentThanaLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimPresentThanaLabel.setText("Present Thana   :");
        getContentPane().add(VictimPresentThanaLabel);
        VictimPresentThanaLabel.setBounds(80, 590, 190, 25);

        VictimPresentAddressLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentAddressLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimPresentAddressLabel.setText("Present Address* : ");
        getContentPane().add(VictimPresentAddressLabel);
        VictimPresentAddressLabel.setBounds(80, 540, 190, 25);

        VictimDistrictLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimDistrictLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimDistrictLabel.setText("District*             : ");
        getContentPane().add(VictimDistrictLabel);
        VictimDistrictLabel.setBounds(80, 480, 180, 25);

        VictimThanaLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimThanaLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimThanaLabel.setText("Thana*               : ");
        getContentPane().add(VictimThanaLabel);
        VictimThanaLabel.setBounds(80, 420, 180, 25);

        VictimVillageLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimVillageLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimVillageLabel.setText("Village               : ");
        getContentPane().add(VictimVillageLabel);
        VictimVillageLabel.setBounds(80, 350, 180, 25);

        VictimFatherLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimFatherLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimFatherLabel.setText("Father's Name   :");
        getContentPane().add(VictimFatherLabel);
        VictimFatherLabel.setBounds(80, 290, 180, 25);

        VictimAgeLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimAgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimAgeLabel.setText("Age*                    :");
        getContentPane().add(VictimAgeLabel);
        VictimAgeLabel.setBounds(80, 230, 180, 25);

        VictimNameLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimNameLabel.setText("Victim Name*     :");
        getContentPane().add(VictimNameLabel);
        VictimNameLabel.setBounds(80, 170, 190, 30);

        VictimDistrictComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VictimDistrictComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--","Barguna", "Barisal","Bhola","Jhalokathi","Potuakhali", "Pirojpur","Bandarban","Brahmanbaria","Chandpur","Chittagong","Comilla", "Coxs Bazar",
            "Feni", "Khagrachhari","Lakshmipur","Noakhali","Rangamati", "Dhaka","Faridpur", "Gazipur","Gopalganj","Kishorganj","Madaripur", "Manikganj",
            "Munshiganj", "Narayanganj","Narsingdi","Rajbari","Shariatpur", "Tangail","Bagerhat", "Chuadanga","Jessore","Jhenaidaha","Khulna", "Kushtia",
            "Magura", "Meherpur","Narail","Satkhira","Jamalpur", "Mymensingh","Netrokona", "Sherpur","Bogura","Joypurhat","Naogan", "Natore",
            "Chapai Nawab Ganj", "Pabna","Rajshahi","Sirajganj","Dinajpur", "Gaibandha","Kurigram","Nilphamari","Lalmonirhaat","Panchagarh","Rangpur","Thakurgaon",
            "Habiganj","Moulovibajar", "Sunamganj","Sylhet"}));
getContentPane().add(VictimDistrictComboBox);
VictimDistrictComboBox.setBounds(300, 470, 680, 40);

VictimPresentDistrictComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
VictimPresentDistrictComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--","Barguna", "Barisal","Bhola","Jhalokathi","Potuakhali", "Pirojpur","Bandarban","Brahmanbaria","Chandpur","Chittagong","Comilla", "Coxs Bazar",
    "Feni", "Khagrachhari","Lakshmipur","Noakhali","Rangamati", "Dhaka","Faridpur", "Gazipur","Gopalganj","Kishorganj","Madaripur", "Manikganj",
    "Munshiganj", "Narayanganj","Narsingdi","Rajbari","Shariatpur", "Tangail","Bagerhat", "Chuadanga","Jessore","Jhenaidaha","Khulna", "Kushtia",
    "Magura", "Meherpur","Narail","Satkhira","Jamalpur", "Mymensingh","Netrokona", "Sherpur","Bogura","Joypurhat","Naogan", "Natore",
    "Chapai Nawab Ganj", "Pabna","Rajshahi","Sirajganj","Dinajpur", "Gaibandha","Kurigram","Nilphamari","Lalmonirhaat","Panchagarh","Rangpur","Thakurgaon",
    "Habiganj","Moulovibajar", "Sunamganj","Sylhet" }));
    getContentPane().add(VictimPresentDistrictComboBox);
    VictimPresentDistrictComboBox.setBounds(300, 650, 680, 40);

    logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/logo.png"))); // NOI18N
    logo_label.setText("jLabel2");
    getContentPane().add(logo_label);
    logo_label.setBounds(1020, 30, 220, 210);

    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/bg_pic.jpg"))); // NOI18N
    jLabel1.setText("jLabel1");
    getContentPane().add(jLabel1);
    jLabel1.setBounds(0, 0, 1240, 880);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VictimNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimNameTextFieldActionPerformed

    private void VictimbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimbackButtonActionPerformed
        // TODO add your handling code here:
        MainPage mObj = new MainPage();
        mObj.show();
        this.setVisible(false);
    }//GEN-LAST:event_VictimbackButtonActionPerformed

    private void VictimSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimSubmitButtonActionPerformed
        // TODO add your handling code here:
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        
            int vic_caseid = Integer.parseInt(VictimCaseIdTextField.getText());
            String vicName= VictimNameTextField.getText();
            String vic_age = VictimAgeTextField.getText();
            String vic_father = VictimFatherTextField.getText() ;
            String vic_vill = VictimVillageTextField.getText() ;
            String vic_tha = VictimThanaTextField.getText();
            
            String District = VictimDistrictComboBox.getSelectedItem().toString();
            int dis = 0;
            if(District.equals("Barguna") )
            {
                dis=8001;
            }
            else if(District.equals("Barisal") )
            {
                dis=8002;
            }
            else if(District.equals("Bhola") )
            {
                dis=8003;
            }
            else if(District.equals("Jhalokathi") )
            {
                dis=8004;
            }
            else if(District.equals("Potuakhali") )
            {
                dis=8005;
            }
            else if(District.equals("Pirojpur") )
            {
                dis=8006;
            }
            else if(District.equals("Bandarban") )
            {
                dis=8007;
            }
            else if(District.equals("Brahmanbaria") )
            {
                dis=8008;
            }
            else if(District.equals("Chandpur") )
            {
                dis=8009;
            }
            else if(District.equals("Chittagong") )
            {
                dis=8010;
            }
            else if(District.equals("Comilla") )
            {
                dis=8011;
            }
            else if(District.equals("Coxs Bazar") )
            {
                dis=8012;
            }
            else if(District.equals("Feni") )
            {
                dis=8013;
            }
            else if(District.equals("Khagrachhari") )
            {
                dis=8014;
            }
            else if(District.equals("Lakshmipur") )
            {
                dis=8015;
            }
            else if(District.equals("Noakhali") )
            {
                dis=8016;
            }
            else if(District.equals("Rangamati") )
            {
                dis=8017;
            }
                else if(District.equals("Dhaka") )
            {
                dis=8018;
            }
            else if(District.equals("Faridpur") )
            {
                dis=8019;
            }
            else if(District.equals("Gazipur") )
            {
                dis=8020;
            }
            else if(District.equals("Gopalganj") )
            {
                dis=8021;
            }
                else if(District.equals("Kishorganj") )
            {
                dis=8022;
            }
            else if(District.equals("Madaripur") )
            {
                dis=8023;
            }
            else if(District.equals("Manikganj") )
            {
                dis=8024;
            }
            else if(District.equals("Munshiganj") )
            {
                dis=8025;
            }
            else if(District.equals("Narayanganj") )
            {
                dis=8026;
            }
            else if(District.equals("Narsingdi") )
            {
                dis=8027;
            }
            else if(District.equals("Rajbari") )
            {
                dis=8028;
            }
            else if(District.equals("Shariatpur") )
            {
                dis=8029;
            }
            else if(District.equals("Tangail") )
            {
                dis=8030;
            }
            else if(District.equals("Bagerhat") )
            {
                dis=8031;
            }
            else if(District.equals("Chuadanga") )
            {
                dis=8032;
            }
            else if(District.equals("Jessore") )
            {
                dis=8033;
            }
             else if(District.equals("Jhenaidaha") )
            {
                dis=8034;
            }
            else if(District.equals("Khulna") )
            {
               dis=8035;
            }
            else if(District.equals("Kushtia") )
            {
                dis=8036;
            }
            else if(District.equals("Magura") )
            {
                dis=8037;
            }
            else if(District.equals("Meherpur") )
            {
                dis=8038;
            }
            else if(District.equals("Narail") )
            {
                dis=8039;
            }
            else if(District.equals("Satkhira") )
            {
                dis=8040;
            }
            else if(District.equals("Jamalpur") )
            {
                dis=8041;
            }
            else if(District.equals("Mymensingh") )
            {
                dis=8042;
            }
            else if(District.equals("Netrokona") )
            {
                dis=8043;
            }
            else if(District.equals("Sherpur") )
            {
                dis=8044;
            }
            else if(District.equals("Bogura") )
            {
                dis=8045;
            }
            else if(District.equals("Joypurhat") )
            {
                dis=8046;
            }
            else if(District.equals("Naogan") )
            {
                dis=8047;
            }
            else if(District.equals("Natore") )
            {
                dis=8048;
            }
            else if(District.equals("Chapai Nawab Ganj") )
            {
                dis=8049;
            }
            else if(District.equals("Pabna") )
            {
                dis=8050;
            }
            else if(District.equals("Rajshahi") )
            {
                dis=8051;
            }
            else if(District.equals("Sirajganj") )
            {
                dis=8052;
            }
            else if(District.equals("Dinajpur") )
            {
               dis=8053;
            }
            else if(District.equals("Gaibandha") )
            {
                dis=8054;
            }
            else if(District.equals("Kurigram") )
            {
                dis=8055;
            }
            else if(District.equals("Nilphamari") )
            {
                dis=8056;
            }
            else if(District.equals("Lalmonirhaat") )
            {
                dis=8057;
            }
            else if(District.equals("Panchagarh") )
            {
                dis=8058;
            }
            else if(District.equals("Rangpur") )
            {
                dis=8059;
            }
            else if(District.equals("Thakurgaon") )
            {
                dis=8060;
            }
            else if(District.equals("Habiganj") )
            {
                dis=8061;
            }
            else if(District.equals("Moulovibajar") )
            {
               dis=8062;
            }
            else if(District.equals("Sunamganj") )
            {
                dis=8063;
            }
            else if(District.equals("Sylhet") )
            {
                dis=8064;
            }
         
            
            String vic_preadd = VictimPresentAddressTextField.getText();
            String vic_pre_tha= VictimPresentThanaTextField.getText();
            
            String pDistrict = VictimPresentDistrictComboBox.getSelectedItem().toString();
            int pdis=0;
            if(pDistrict.equals("Barguna") )
            {
                pdis=8001;
            }
            else if(pDistrict.equals("Barisal") )
            {
                pdis=8002;
            }
            else if(pDistrict.equals("Bhola") )
            {
                pdis=8003;
            }
            else if(pDistrict.equals("Jhalokathi") )
            {
                pdis=8004;
            }
            else if(pDistrict.equals("Potuakhali") )
            {
                pdis=8005;
            }
            else if(pDistrict.equals("Pirojpur") )
            {
                pdis=8006;
            }
            else if(pDistrict.equals("Bandarban") )
            {
                pdis=8007;
            }
            else if(pDistrict.equals("Brahmanbaria") )
            {
                pdis=8008;
            }
            else if(pDistrict.equals("Chandpur") )
            {
                pdis=8009;
            }
            else if(pDistrict.equals("Chittagong") )
            {
                pdis=8010;
            }
            else if(pDistrict.equals("Comilla") )
            {
                pdis=8011;
            }
            else if(pDistrict.equals("Coxs Bazar") )
            {
                pdis=8012;
            }
            else if(pDistrict.equals("Feni") )
            {
                pdis=8013;
            }
            else if(pDistrict.equals("Khagrachhari") )
            {
                pdis=8014;
            }
            else if(pDistrict.equals("Lakshmipur") )
            {
                pdis=8015;
            }
            else if(pDistrict.equals("Noakhali") )
            {
                pdis=8016;
            }
            else if(pDistrict.equals("Rangamati") )
            {
                pdis=8017;
            }
                else if(pDistrict.equals("Dhaka") )
            {
                pdis=8018;
            }
            else if(pDistrict.equals("Faridpur") )
            {
                pdis=8019;
            }
            else if(pDistrict.equals("Gazipur") )
            {
                pdis=8020;
            }
            else if(pDistrict.equals("Gopalganj") )
            {
                pdis=8021;
            }
                else if(pDistrict.equals("Kishorganj") )
            {
                pdis=8022;
            }
            else if(pDistrict.equals("Madaripur") )
            {
                pdis=8023;
            }
            else if(pDistrict.equals("Manikganj") )
            {
                pdis=8024;
            }
            else if(pDistrict.equals("Munshiganj") )
            {
                pdis=8025;
            }
            else if(pDistrict.equals("Narayanganj") )
            {
                pdis=8026;
            }
            else if(pDistrict.equals("Narsingdi") )
            {
                pdis=8027;
            }
            else if(pDistrict.equals("Rajbari") )
            {
                pdis=8028;
            }
            else if(pDistrict.equals("Shariatpur") )
            {
                pdis=8029;
            }
            else if(pDistrict.equals("Tangail") )
            {
                pdis=8030;
            }
            else if(pDistrict.equals("Bagerhat") )
            {
                pdis=8031;
            }
            else if(pDistrict.equals("Chuadanga") )
            {
                pdis=8032;
            }
            else if(pDistrict.equals("Jessore") )
            {
                pdis=8033;
            }
             else if(pDistrict.equals("Jhenaidaha") )
            {
                pdis=8034;
            }
            else if(pDistrict.equals("Khulna") )
            {
               pdis=8035;
            }
            else if(pDistrict.equals("Kushtia") )
            {
                pdis=8036;
            }
            else if(pDistrict.equals("Magura") )
            {
                pdis=8037;
            }
            else if(pDistrict.equals("Meherpur") )
            {
                pdis=8038;
            }
            else if(pDistrict.equals("Narail") )
            {
                pdis=8039;
            }
            else if(pDistrict.equals("Satkhira") )
            {
                pdis=8040;
            }
            else if(pDistrict.equals("Jamalpur") )
            {
                pdis=8041;
            }
            else if(pDistrict.equals("Mymensingh") )
            {
                pdis=8042;
            }
            else if(pDistrict.equals("Netrokona") )
            {
                pdis=8043;
            }
            else if(pDistrict.equals("Sherpur") )
            {
                pdis=8044;
            }
            else if(pDistrict.equals("Bogura") )
            {
                pdis=8045;
            }
            else if(pDistrict.equals("Joypurhat") )
            {
                pdis=8046;
            }
            else if(pDistrict.equals("Naogan") )
            {
                pdis=8047;
            }
            else if(pDistrict.equals("Natore") )
            {
                pdis=8048;
            }
            else if(pDistrict.equals("Chapai Nawab Ganj") )
            {
                pdis=8049;
            }
            else if(pDistrict.equals("Pabna") )
            {
                pdis=8050;
            }
            else if(pDistrict.equals("Rajshahi") )
            {
                pdis=8051;
            }
            else if(pDistrict.equals("Sirajganj") )
            {
                pdis=8052;
            }
            else if(pDistrict.equals("Dinajpur") )
            {
               pdis=8053;
            }
            else if(pDistrict.equals("Gaibandha") )
            {
                pdis=8054;
            }
            else if(pDistrict.equals("Kurigram") )
            {
                pdis=8055;
            }
            else if(pDistrict.equals("Nilphamari") )
            {
                pdis=8056;
            }
            else if(pDistrict.equals("Lalmonirhaat") )
            {
                pdis=8057;
            }
            else if(pDistrict.equals("Panchagarh") )
            {
                pdis=8058;
            }
            else if(pDistrict.equals("Rangpur") )
            {
                pdis=8059;
            }
            else if(pDistrict.equals("Thakurgaon") )
            {
                pdis=8060;
            }
            else if(pDistrict.equals("Habiganj") )
            {
                pdis=8061;
            }
            else if(pDistrict.equals("Moulovibajar") )
            {
               pdis=8062;
            }
            else if(pDistrict.equals("Sunamganj") )
            {
                pdis=8063;
            }
            else if(pDistrict.equals("Sylhet") )
            {
                pdis=8064;
            }
            
            String vic_mob=VictimMobileNoTextField.getText();
                                                                                                                                                                                                                                                      
            String updatequery= "UPDATE Victim SET CaseNo='"+vic_caseid+"', VictimName='"+vicName+"', Age='"+vic_age+"',FathersName ='"+vic_father+"',Village='"+vic_vill+"',Thana='"+vic_tha+"',DistrictId ='"+dis+"',PresentAddress ='"+vic_preadd+"',PresentThana='"+vic_pre_tha+"', PresentDistrictId ='"+pdis+"', MobileNo ='"+vic_mob+"' WHERE CaseNo='"+vic_caseid+"' ";
            
        try {
            
            Statement st = (Statement) cnObj.connection.createStatement();
            st.executeUpdate(updatequery);
            JOptionPane.showMessageDialog(null,"Updated SUCCESSFULLY");
        } catch (SQLException ex) {
            Logger.getLogger(AccusedUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            

        
        
    }//GEN-LAST:event_VictimSubmitButtonActionPerformed

    private void VictimMobileNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimMobileNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimMobileNoTextFieldActionPerformed

    private void VictimVillageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimVillageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimVillageTextFieldActionPerformed

    private void VictimCaseIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimCaseIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimCaseIdTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VictimPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VictimAgeLabel;
    public javax.swing.JTextField VictimAgeTextField;
    public javax.swing.JTextField VictimCaseIdTextField;
    public javax.swing.JComboBox<String> VictimDistrictComboBox;
    private javax.swing.JLabel VictimDistrictLabel;
    private javax.swing.JLabel VictimFatherLabel;
    public javax.swing.JTextField VictimFatherTextField;
    public javax.swing.JTextField VictimMobileNoTextField;
    private javax.swing.JLabel VictimNameLabel;
    private javax.swing.JLabel VictimNameLabel1;
    public javax.swing.JTextField VictimNameTextField;
    private javax.swing.JLabel VictimPresentAddressLabel;
    public javax.swing.JTextField VictimPresentAddressTextField;
    public javax.swing.JComboBox<String> VictimPresentDistrictComboBox;
    private javax.swing.JLabel VictimPresentDistrictLabel;
    private javax.swing.JLabel VictimPresentDistrictLabel1;
    private javax.swing.JLabel VictimPresentThanaLabel;
    public javax.swing.JTextField VictimPresentThanaTextField;
    private javax.swing.JButton VictimSubmitButton;
    private javax.swing.JLabel VictimThanaLabel;
    public javax.swing.JTextField VictimThanaTextField;
    private javax.swing.JLabel VictimVillageLabel;
    public javax.swing.JTextField VictimVillageTextField;
    private javax.swing.JButton VictimbackButton;
    private javax.swing.JLabel VictimformLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo_label;
    // End of variables declaration//GEN-END:variables
}
