package PoliceStationManagement;
import SQLPackage.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class VictimPage extends javax.swing.JFrame {

    /**
     * Creates new form VictimPage
     */
    public VictimPage() {
        initComponents();
        setSize(1250,885);
        setTitle("Victim");
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VictimNameLabel1 = new javax.swing.JLabel();
        VictimCaseIdTextField = new javax.swing.JTextField();
        VictimPresentDistrictLabel1 = new javax.swing.JLabel();
        VictimMobileNoTextField = new javax.swing.JTextField();
        VictimPresentAddressTextField = new javax.swing.JTextField();
        VictimSubmitButton = new javax.swing.JButton();
        VictimbackButton = new javax.swing.JButton();
        VictimPresentThanaTextField = new javax.swing.JTextField();
        VictimThanaTextField = new javax.swing.JTextField();
        VictimVillageTextField = new javax.swing.JTextField();
        VictimFatherTextField = new javax.swing.JTextField();
        VictimAgeTextField = new javax.swing.JTextField();
        VictimNameTextField = new javax.swing.JTextField();
        VictimformLabel = new javax.swing.JLabel();
        VictimPresentDistrictLabel = new javax.swing.JLabel();
        VictimPresentThanaLabel = new javax.swing.JLabel();
        VictimPresentAddressLabel = new javax.swing.JLabel();
        VictimDistrictLabel = new javax.swing.JLabel();
        VictimThanaLabel = new javax.swing.JLabel();
        VictimVillageLabel = new javax.swing.JLabel();
        VictimFatherLabel = new javax.swing.JLabel();
        VictimAgeLabel = new javax.swing.JLabel();
        VictimNameLabel = new javax.swing.JLabel();
        VictimDistrictComboBox = new javax.swing.JComboBox<>();
        VictimPresentDistrictComboBox = new javax.swing.JComboBox<>();
        logo_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 885));
        getContentPane().setLayout(null);

        VictimNameLabel1.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        VictimNameLabel1.setText("Case No*     :");
        getContentPane().add(VictimNameLabel1);
        VictimNameLabel1.setBounds(80, 110, 190, 30);

        VictimCaseIdTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimCaseIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimCaseIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimCaseIdTextField);
        VictimCaseIdTextField.setBounds(300, 110, 680, 40);

        VictimPresentDistrictLabel1.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentDistrictLabel1.setForeground(new java.awt.Color(240, 240, 240));
        VictimPresentDistrictLabel1.setText("Mobile No*  : ");
        getContentPane().add(VictimPresentDistrictLabel1);
        VictimPresentDistrictLabel1.setBounds(80, 710, 190, 25);

        VictimMobileNoTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimMobileNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimMobileNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimMobileNoTextField);
        VictimMobileNoTextField.setBounds(300, 710, 680, 40);

        VictimPresentAddressTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimPresentAddressTextField);
        VictimPresentAddressTextField.setBounds(300, 530, 680, 40);

        VictimSubmitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimSubmitButton.setText("Submit");
        VictimSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimSubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VictimSubmitButton);
        VictimSubmitButton.setBounds(1000, 770, 200, 50);

        VictimbackButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimbackButton.setText("Back");
        VictimbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimbackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VictimbackButton);
        VictimbackButton.setBounds(80, 770, 180, 50);

        VictimPresentThanaTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimPresentThanaTextField);
        VictimPresentThanaTextField.setBounds(300, 590, 680, 40);

        VictimThanaTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimThanaTextField);
        VictimThanaTextField.setBounds(300, 410, 680, 40);

        VictimVillageTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimVillageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimVillageTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimVillageTextField);
        VictimVillageTextField.setBounds(300, 350, 680, 40);

        VictimFatherTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimFatherTextField);
        VictimFatherTextField.setBounds(300, 290, 680, 40);

        VictimAgeTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(VictimAgeTextField);
        VictimAgeTextField.setBounds(300, 230, 680, 40);

        VictimNameTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VictimNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VictimNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VictimNameTextField);
        VictimNameTextField.setBounds(300, 170, 680, 40);

        VictimformLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        VictimformLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimformLabel.setText("Victim Form");
        getContentPane().add(VictimformLabel);
        VictimformLabel.setBounds(470, 30, 310, 60);

        VictimPresentDistrictLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentDistrictLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimPresentDistrictLabel.setText("Present District  : ");
        getContentPane().add(VictimPresentDistrictLabel);
        VictimPresentDistrictLabel.setBounds(80, 650, 190, 25);

        VictimPresentThanaLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentThanaLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimPresentThanaLabel.setText("Present Thana   :");
        getContentPane().add(VictimPresentThanaLabel);
        VictimPresentThanaLabel.setBounds(80, 590, 190, 25);

        VictimPresentAddressLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimPresentAddressLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimPresentAddressLabel.setText("Present Address* : ");
        getContentPane().add(VictimPresentAddressLabel);
        VictimPresentAddressLabel.setBounds(80, 540, 190, 25);

        VictimDistrictLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimDistrictLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimDistrictLabel.setText("District*             : ");
        getContentPane().add(VictimDistrictLabel);
        VictimDistrictLabel.setBounds(80, 480, 180, 25);

        VictimThanaLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimThanaLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimThanaLabel.setText("Thana*               : ");
        getContentPane().add(VictimThanaLabel);
        VictimThanaLabel.setBounds(80, 420, 180, 25);

        VictimVillageLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimVillageLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimVillageLabel.setText("Village               : ");
        getContentPane().add(VictimVillageLabel);
        VictimVillageLabel.setBounds(80, 350, 180, 25);

        VictimFatherLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimFatherLabel.setForeground(new java.awt.Color(240, 240, 240));
        VictimFatherLabel.setText("Father's Name   :");
        getContentPane().add(VictimFatherLabel);
        VictimFatherLabel.setBounds(80, 290, 180, 25);

        VictimAgeLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimAgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimAgeLabel.setText("Age*                    :");
        getContentPane().add(VictimAgeLabel);
        VictimAgeLabel.setBounds(80, 230, 180, 25);

        VictimNameLabel.setFont(new java.awt.Font("Adobe Hebrew", 0, 24)); // NOI18N
        VictimNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        VictimNameLabel.setText("Victim Name*     :");
        getContentPane().add(VictimNameLabel);
        VictimNameLabel.setBounds(80, 170, 190, 30);

        VictimDistrictComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VictimDistrictComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--","Barguna", "Barisal","Bhola","Jhalokathi","Potuakhali", "Pirojpur","Bandarban","Brahmanbaria","Chandpur","Chittagong","Comilla", "Coxs Bazar",
            "Feni", "Khagrachhari","Lakshmipur","Noakhali","Rangamati", "Dhaka","Faridpur", "Gazipur","Gopalganj","Kishorganj","Madaripur", "Manikganj",
            "Munshiganj", "Narayanganj","Narsingdi","Rajbari","Shariatpur", "Tangail","Bagerhat", "Chuadanga","Jessore","Jhenaidaha","Khulna", "Kushtia",
            "Magura", "Meherpur","Narail","Satkhira","Jamalpur", "Mymensingh","Netrokona", "Sherpur","Bogura","Joypurhat","Naogan", "Natore",
            "Chapai Nawab Ganj", "Pabna","Rajshahi","Sirajganj","Dinajpur", "Gaibandha","Kurigram","Nilphamari","Lalmonirhaat","Panchagarh","Rangpur","Thakurgaon",
            "Habiganj","Moulovibajar", "Sunamganj","Sylhet"}));
getContentPane().add(VictimDistrictComboBox);
VictimDistrictComboBox.setBounds(300, 470, 680, 40);

VictimPresentDistrictComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
VictimPresentDistrictComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--","Barguna", "Barisal","Bhola","Jhalokathi","Potuakhali", "Pirojpur","Bandarban","Brahmanbaria","Chandpur","Chittagong","Comilla", "Coxs Bazar",
    "Feni", "Khagrachhari","Lakshmipur","Noakhali","Rangamati", "Dhaka","Faridpur", "Gazipur","Gopalganj","Kishorganj","Madaripur", "Manikganj",
    "Munshiganj", "Narayanganj","Narsingdi","Rajbari","Shariatpur", "Tangail","Bagerhat", "Chuadanga","Jessore","Jhenaidaha","Khulna", "Kushtia",
    "Magura", "Meherpur","Narail","Satkhira","Jamalpur", "Mymensingh","Netrokona", "Sherpur","Bogura","Joypurhat","Naogan", "Natore",
    "Chapai Nawab Ganj", "Pabna","Rajshahi","Sirajganj","Dinajpur", "Gaibandha","Kurigram","Nilphamari","Lalmonirhaat","Panchagarh","Rangpur","Thakurgaon",
    "Habiganj","Moulovibajar", "Sunamganj","Sylhet" }));
    getContentPane().add(VictimPresentDistrictComboBox);
    VictimPresentDistrictComboBox.setBounds(300, 650, 680, 40);

    logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/logo.png"))); // NOI18N
    logo_label.setText("jLabel2");
    getContentPane().add(logo_label);
    logo_label.setBounds(1020, 30, 220, 210);

    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PoliceStationManagement/bg_pic.jpg"))); // NOI18N
    jLabel1.setText("jLabel1");
    getContentPane().add(jLabel1);
    jLabel1.setBounds(0, 0, 1240, 880);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VictimNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimNameTextFieldActionPerformed

    private void VictimbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimbackButtonActionPerformed
        // TODO add your handling code here:
        MainPage mObj = new MainPage();
        mObj.show();
        this.setVisible(false);
    }//GEN-LAST:event_VictimbackButtonActionPerformed

    private void VictimSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimSubmitButtonActionPerformed
        // TODO add your handling code here:
        ConnectMSSQL cnObj = new ConnectMSSQL();
        cnObj.connectDB();
        
        String query = "INSERT INTO Victim(CaseNo,VictimName,Age,FathersName,Village,Thana,DistrictId,PresentAddress,PresentThana,PresentDistrictId,MobileNo) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst;
        try {
            pst = (PreparedStatement) cnObj.connection.prepareStatement(query);
            pst.setString(1,VictimCaseIdTextField.getText());
            pst.setString(2,VictimNameTextField.getText());
            pst.setString(3,VictimAgeTextField.getText());
            pst.setString(4,VictimFatherTextField.getText() );
            pst.setString(5,VictimVillageTextField.getText() );
            pst.setString(6,VictimThanaTextField.getText());
            
            String District = VictimDistrictComboBox.getSelectedItem().toString();
            if(District.equals("Barguna") )
            {
                pst.setString(7,"8001");
            }
            else if(District.equals("Barisal") )
            {
                pst.setString(7,"8002");
            }
            else if(District.equals("Bhola") )
            {
                pst.setString(7,"8003");
            }
            else if(District.equals("Jhalokathi") )
            {
                pst.setString(7,"8004");
            }
            else if(District.equals("Potuakhali") )
            {
                pst.setString(7,"8005");
            }
            else if(District.equals("Pirojpur") )
            {
                pst.setString(7,"8006");
            }
            else if(District.equals("Bandarban") )
            {
                pst.setString(7,"8007");
            }
            else if(District.equals("Brahmanbaria") )
            {
                pst.setString(7,"8008");
            }
            else if(District.equals("Chandpur") )
            {
                pst.setString(7,"8009");
            }
            else if(District.equals("Chittagong") )
            {
                pst.setString(7,"8010");
            }
            else if(District.equals("Comilla") )
            {
                pst.setString(7,"8011");
            }
            else if(District.equals("Coxs Bazar") )
            {
                pst.setString(7,"8012");
            }
            else if(District.equals("Feni") )
            {
                pst.setString(7,"8013");
            }
            else if(District.equals("Khagrachhari") )
            {
                pst.setString(7,"8014");
            }
            else if(District.equals("Lakshmipur") )
            {
                pst.setString(7,"8015");
            }
            else if(District.equals("Noakhali") )
            {
                pst.setString(7,"8016");
            }
            else if(District.equals("Rangamati") )
            {
                pst.setString(7,"8017");
            }
                else if(District.equals("Dhaka") )
            {
                pst.setString(7,"8018");
            }
            else if(District.equals("Faridpur") )
            {
                pst.setString(7,"8019");
            }
            else if(District.equals("Gazipur") )
            {
                pst.setString(7,"8020");
            }
            else if(District.equals("Gopalganj") )
            {
                pst.setString(7,"8021");
            }
                else if(District.equals("Kishorganj") )
            {
                pst.setString(7,"8022");
            }
            else if(District.equals("Madaripur") )
            {
                pst.setString(7,"8023");
            }
            else if(District.equals("Manikganj") )
            {
                pst.setString(7,"8024");
            }
            else if(District.equals("Munshiganj") )
            {
                pst.setString(7,"8025");
            }
            else if(District.equals("Narayanganj") )
            {
                pst.setString(7,"8026");
            }
            else if(District.equals("Narsingdi") )
            {
                pst.setString(7,"8027");
            }
            else if(District.equals("Rajbari") )
            {
                pst.setString(7,"8028");
            }
            else if(District.equals("Shariatpur") )
            {
                pst.setString(7,"8029");
            }
            else if(District.equals("Tangail") )
            {
                pst.setString(7,"8030");
            }
            else if(District.equals("Bagerhat") )
            {
                pst.setString(7,"8031");
            }
            else if(District.equals("Chuadanga") )
            {
                pst.setString(7,"8032");
            }
            else if(District.equals("Jessore") )
            {
                pst.setString(7,"8033");
            }
             else if(District.equals("Jhenaidaha") )
            {
                pst.setString(7,"8034");
            }
            else if(District.equals("Khulna") )
            {
                pst.setString(7,"8035");
            }
            else if(District.equals("Kushtia") )
            {
                pst.setString(7,"8036");
            }
            else if(District.equals("Magura") )
            {
                pst.setString(7,"8037");
            }
            else if(District.equals("Meherpur") )
            {
                pst.setString(7,"8038");
            }
            else if(District.equals("Narail") )
            {
                pst.setString(7,"8039");
            }
            else if(District.equals("Satkhira") )
            {
                pst.setString(7,"8040");
            }
            else if(District.equals("Jamalpur") )
            {
                pst.setString(7,"8041");
            }
            else if(District.equals("Mymensingh") )
            {
                pst.setString(7,"8042");
            }
            else if(District.equals("Netrokona") )
            {
                pst.setString(7,"8043");
            }
            else if(District.equals("Sherpur") )
            {
                pst.setString(7,"8044");
            }
            else if(District.equals("Bogura") )
            {
                pst.setString(7,"8045");
            }
            else if(District.equals("Joypurhat") )
            {
                pst.setString(7,"8046");
            }
            else if(District.equals("Naogan") )
            {
                pst.setString(7,"8047");
            }
            else if(District.equals("Natore") )
            {
                pst.setString(7,"8048");
            }
            else if(District.equals("Chapai Nawab Ganj") )
            {
                pst.setString(7,"8049");
            }
            else if(District.equals("Pabna") )
            {
                pst.setString(7,"8050");
            }
            else if(District.equals("Rajshahi") )
            {
                pst.setString(7,"8051");
            }
            else if(District.equals("Sirajganj") )
            {
                pst.setString(7,"8052");
            }
            else if(District.equals("Dinajpur") )
            {
                pst.setString(7,"8053");
            }
            else if(District.equals("Gaibandha") )
            {
                pst.setString(7,"8054");
            }
            else if(District.equals("Kurigram") )
            {
                pst.setString(7,"8055");
            }
            else if(District.equals("Nilphamari") )
            {
                pst.setString(7,"8056");
            }
            else if(District.equals("Lalmonirhaat") )
            {
                pst.setString(7,"8057");
            }
            else if(District.equals("Panchagarh") )
            {
                pst.setString(7,"8058");
            }
            else if(District.equals("Rangpur") )
            {
                pst.setString(7,"8059");
            }
            else if(District.equals("Thakurgaon") )
            {
                pst.setString(7,"8060");
            }
            else if(District.equals("Habiganj") )
            {
                pst.setString(7,"8061");
            }
            else if(District.equals("Moulovibajar") )
            {
                pst.setString(7,"8062");
            }
            else if(District.equals("Sunamganj") )
            {
                pst.setString(7,"8063");
            }
            else if(District.equals("Sylhet") )
            {
                pst.setString(7,"8064");
            }
          
            
            pst.setString(8,VictimPresentAddressTextField.getText());
            pst.setString(9,VictimPresentThanaTextField.getText());
            
            String pDistrict = VictimPresentDistrictComboBox.getSelectedItem().toString();
            if(pDistrict.equals("Barguna") )
            {
                pst.setString(10,"8001");
            }
            else if(pDistrict.equals("Barisal") )
            {
                pst.setString(10,"8002");
            }
            else if(pDistrict.equals("Bhola") )
            {
                pst.setString(10,"8003");
            }
            else if(pDistrict.equals("Jhalokathi") )
            {
                pst.setString(10,"8004");
            }
            else if(pDistrict.equals("Potuakhali") )
            {
                pst.setString(10,"8005");
            }
            else if(pDistrict.equals("Pirojpur") )
            {
                pst.setString(10,"8006");
            }
            else if(pDistrict.equals("Bandarban") )
            {
                pst.setString(10,"8007");
            }
            else if(pDistrict.equals("Brahmanbaria") )
            {
                pst.setString(10,"8008");
            }
            else if(pDistrict.equals("Chandpur") )
            {
                pst.setString(10,"8009");
            }
            else if(pDistrict.equals("Chittagong") )
            {
                pst.setString(10,"8010");
            }
            else if(pDistrict.equals("Comilla") )
            {
                pst.setString(10,"8011");
            }
            else if(pDistrict.equals("Coxs Bazar") )
            {
                pst.setString(10,"8012");
            }
            else if(pDistrict.equals("Feni") )
            {
                pst.setString(10,"8013");
            }
            else if(pDistrict.equals("Khagrachhari") )
            {
                pst.setString(10,"8014");
            }
            else if(pDistrict.equals("Lakshmipur") )
            {
                pst.setString(10,"8015");
            }
            else if(pDistrict.equals("Noakhali") )
            {
                pst.setString(10,"8016");
            }
            else if(pDistrict.equals("Rangamati") )
            {
                pst.setString(10,"8017");
            }
            else if(pDistrict.equals("Dhaka") )
            {
                pst.setString(10,"8018");
            }
            else if(pDistrict.equals("Faridpur") )
            {
                pst.setString(10,"8019");
            }
            else if(pDistrict.equals("Gazipur") )
            {
                pst.setString(10,"8020");
            }
            else if(pDistrict.equals("Gopalganj") )
            {
                pst.setString(10,"8021");
            }
            else if(pDistrict.equals("Kishorganj") )
            {
                pst.setString(10,"8022");
            }
            else if(pDistrict.equals("Madaripur") )
            {
                pst.setString(10,"8023");
            }
            else if(pDistrict.equals("Manikganj") )
            {
                pst.setString(10,"8024");
            }
            else if(pDistrict.equals("Munshiganj") )
            {
                pst.setString(10,"8025");
            }
            else if(pDistrict.equals("Narayanganj") )
            {
                pst.setString(10,"8026");
            }
            else if(pDistrict.equals("Narsingdi") )
            {
                pst.setString(10,"8027");
            }
            else if(pDistrict.equals("Rajbari") )
            {
                pst.setString(10,"8028");
            }
            else if(pDistrict.equals("Shariatpur") )
            {
                pst.setString(10,"8029");
            }
            else if(pDistrict.equals("Tangail") )
            {
                pst.setString(10,"8030");
            }
            else if(pDistrict.equals("Bagerhat") )
            {
                pst.setString(10,"8031");
            }
            else if(pDistrict.equals("Chuadanga") )
            {
                pst.setString(10,"8032");
            }
            else if(pDistrict.equals("Jessore") )
            {
                pst.setString(10,"8033");
            }
            else if(pDistrict.equals("Jhenaidaha") )
            {
                pst.setString(10,"8034");
            }
            else if(pDistrict.equals("Khulna") )
            {
                pst.setString(10,"8035");
            }
            else if(pDistrict.equals("Kushtia") )
            {
                pst.setString(10,"8036");
            }
            else if(pDistrict.equals("Magura") )
            {
                pst.setString(10,"8037");
            }
            else if(pDistrict.equals("Meherpur") )
            {
                pst.setString(10,"8038");
            }
            else if(pDistrict.equals("Narail") )
            {
                pst.setString(10,"8039");
            }
            else if(pDistrict.equals("Satkhira") )
            {
                pst.setString(10,"8040");
            }
            else if(pDistrict.equals("Jamalpur") )
            {
                pst.setString(10,"8041");
            }
            else if(pDistrict.equals("Mymensingh") )
            {
                pst.setString(10,"8042");
            }
            else if(pDistrict.equals("Netrokona") )
            {
                pst.setString(10,"8043");
            }
            else if(pDistrict.equals("Sherpur") )
            {
                pst.setString(10,"8044");
            }
            else if(pDistrict.equals("Bogura") )
            {
                pst.setString(10,"8045");
            }
            else if(pDistrict.equals("Joypurhat") )
            {
                pst.setString(10,"8046");
            }
            else if(pDistrict.equals("Naogan") )
            {
                pst.setString(10,"8047");
            }
            else if(pDistrict.equals("Natore") )
            {
                pst.setString(10,"8048");
            }
            else if(pDistrict.equals("Chapai Nawab Ganj") )
            {
                pst.setString(10,"8049");
            }
            else if(pDistrict.equals("Pabna") )
            {
                pst.setString(10,"8050");
            }
            else if(pDistrict.equals("Rajshahi") )
            {
                pst.setString(10,"8051");
            }
            else if(pDistrict.equals("Sirajganj") )
            {
                pst.setString(10,"8052");
            }
            else if(pDistrict.equals("Dinajpur") )
            {
                pst.setString(10,"8053");
            }
            else if(pDistrict.equals("Gaibandha") )
            {
                pst.setString(10,"8054");
            }
            else if(pDistrict.equals("Kurigram") )
            {
                pst.setString(10,"8055");
            }
            else if(pDistrict.equals("Nilphamari") )
            {
                pst.setString(10,"8056");
            }
            else if(pDistrict.equals("Lalmonirhaat") )
            {
                pst.setString(10,"8057");
            }
            else if(pDistrict.equals("Panchagarh") )
            {
                pst.setString(10,"8058");
            }
            else if(pDistrict.equals("Rangpur") )
            {
                pst.setString(10,"8059");
            }
            else if(pDistrict.equals("Thakurgaon") )
            {
                pst.setString(10,"8060");
            }
            else if(pDistrict.equals("Habiganj") )
            {
                pst.setString(10,"8061");
            }
            else if(pDistrict.equals("Moulovibajar") )
            {
                pst.setString(10,"8062");
            }
            else if(pDistrict.equals("Sunamganj") )
            {
                pst.setString(10,"8063");
            }
            else if(pDistrict.equals("Sylhet") )
            {
                pst.setString(10,"8064");
            }
            
            pst.setString(11,VictimMobileNoTextField.getText());
            
            if((VictimCaseIdTextField.getText().equals(""))||(VictimMobileNoTextField.getText().equals(""))||(VictimNameTextField.getText().equals("")) || (VictimAgeTextField.getText().equals("")) || (VictimThanaTextField.getText().equals("")) || (District.equals("")) || (VictimPresentAddressTextField.getText().equals("")) ){
                JOptionPane.showMessageDialog(null,"Please fill up the required(*) text fields!!");
            }
            else{
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Inserted SUCCESSFULLY");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VictimPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_VictimSubmitButtonActionPerformed

    private void VictimMobileNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimMobileNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimMobileNoTextFieldActionPerformed

    private void VictimVillageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimVillageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimVillageTextFieldActionPerformed

    private void VictimCaseIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VictimCaseIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VictimCaseIdTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VictimPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VictimPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VictimAgeLabel;
    private javax.swing.JTextField VictimAgeTextField;
    private javax.swing.JTextField VictimCaseIdTextField;
    private javax.swing.JComboBox<String> VictimDistrictComboBox;
    private javax.swing.JLabel VictimDistrictLabel;
    private javax.swing.JLabel VictimFatherLabel;
    private javax.swing.JTextField VictimFatherTextField;
    private javax.swing.JTextField VictimMobileNoTextField;
    private javax.swing.JLabel VictimNameLabel;
    private javax.swing.JLabel VictimNameLabel1;
    private javax.swing.JTextField VictimNameTextField;
    private javax.swing.JLabel VictimPresentAddressLabel;
    private javax.swing.JTextField VictimPresentAddressTextField;
    private javax.swing.JComboBox<String> VictimPresentDistrictComboBox;
    private javax.swing.JLabel VictimPresentDistrictLabel;
    private javax.swing.JLabel VictimPresentDistrictLabel1;
    private javax.swing.JLabel VictimPresentThanaLabel;
    private javax.swing.JTextField VictimPresentThanaTextField;
    private javax.swing.JButton VictimSubmitButton;
    private javax.swing.JLabel VictimThanaLabel;
    private javax.swing.JTextField VictimThanaTextField;
    private javax.swing.JLabel VictimVillageLabel;
    private javax.swing.JTextField VictimVillageTextField;
    private javax.swing.JButton VictimbackButton;
    private javax.swing.JLabel VictimformLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo_label;
    // End of variables declaration//GEN-END:variables
}
